name: Docs Sync

on:
  push:
    branches: [main]
    paths: ["docs/**"]
  workflow_dispatch:

jobs:
  sync:
    uses: TIMMYG-Studios/workflows/.gitea/workflows/docs.yml@main
    with:
      docs_slug: tLib
    secrets: inherit
